export const API_BASE_URL = "https://inventory.pootechnologies.tech/api/inventory";
export const API_BASE_URL_LOGIN = "https://inventory.pootechnologies.tech/";
export const IMAGE_BASE_URL = "https://inventory.pootechnologies.tech/";
export const API_BASE_RENDER_URL = "http://poo-drf.onrender.com/api";
export const API_BASE_PROFILE = "https://inventory.pootechnologies.tech/auth";

export const API_ENDPOINTS = {
  LOGIN: "/token/",
  REFRESH: "/token/refresh/",
  LOGIN_TENANT: "tenants/token/",
  TENANT_PROVISION: "tenants/provision-tenant/",
  TENANT_GROUPS: "tenant/groups/",
  TENANT_USERS: "tenant-users/",
  PRODUCTS: "/products",
  PRODUCT_LOG: "/product_log/",
  CATEGORIES: "/category",
  CUSTOMERS: "/customers",
  ORDERS: "/orders",
  CREDIT: "/orders-credit",
  SUPPLIERS: "/suppliers",
  PROFILE: "/user/profile/",
  CHANGEPASSWORD: "/user/change_password/",
  ORDERITEMS: "/orderitems",
  ORDERITEMSCREDIT: "/orderitems-credit",
  USER: "/user/",
  USERPROFILE: "/user/profile/",
  REVENUE: "/revenue",
  REPORT: "/report",
  ALLORDERS: "/orderitems",
  COMPANY: "/company",
  PROFIT: "/profit",
  LOGS: "/order_log/",
  STOCK_LIST: "/stock/",
  STOCK_COUNT: "/stock_count/",
  EXPENSE_TYPE: "expense_type",
  OTHER_EXPENSE: "/other_expenses",
  PRODUCT_COST: "/product_cost/",
  TOTAL_EXPENSES: "/total_expense/",
  PURCHASE_EXPENSES: "/purchase-expenses/",
  PURCHASE_PRODUCTS: "/purchase-products/",
  PURCHASE_SUPPLIERS: "/purchase-suppliers/",
  RECEIPT: "/orders/",
  PERFORMA: "/performa/",
  PERFORMA_ITEMS: "/performaitems/",
  SALES_DASHBOARD: "/sales-dashboard/",
  RECENT_ORDERS: "/recent-orders/",
  SALES_MAN_REVENUE: "/salesperson-revenue/",
  SALES_MAN_TOTAL_ORDERS: "/salesperson-total-orders/",
  DAILY_SALES: "/daily-sales/",
  SALES_MAN_DAILY_SALES: "/daily-sales-per-user/",
  SALES_MAN_WEEKLY_SALES: "/weekly-sales-per-user/",
  SALES_MAN_MONTHLY_SALES: "/monthly-sales-per-user/",
  SALES_MAN_YEARLY_SALES: "/yearly-sales-per-user/",
  WEEKLY_SALES_MANAGER: "/weekly-sales/",
  MONTHLY_SALES_MANAGER: "/monthly-sales/",
  YEARLY_SALES_MANAGER: "/yearly-sales/",
  PURCHASE_SUPPLIERS_LOGS: "/purchase-suppliers/",
  EXPENSE_LOGS: "/purchase-expenses/",
  ORDER_LOGS: "/orders/",
  PERFORMA_CUSTOMER: "/performa-customers/",
  PERFORMA_PERFORMAS: "/performa-performas/",
  PERFORMA_PRODUCTS: "/performa-products/",
  PRODUCT_BUNLDE: "/product_with_bundle/",
  PRODUCT_COMPONENT: "/product_with_out_bundle/",
  BUNDLE_COMPONENTS: "/bundles/"
};
